sonar.projectKey=tthaisvale_DevOps-Homestead
sonar.organization=tthaisvale
sonar.host.url=https://sonarcloud.io
sonar.language=java
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/jacoco/jacoco.xml
